In [1]:
import pandas as pd

pip install openpyxl

In [5]:
df = pd.read_excel('GUIAS DE ITBI PAGAS (2024).xlsx')

df.head(10)

,N° do Cadastro (SQL),Nome do Logradouro,Número,Complemento,Bairro,Referência,CEP,Natureza de Transação,Valor de Transação (declarado pelo contribuinte),Data de Transação,...,Situação do SQL,Área do Terreno (m2),Testada (m),Fração Ideal,Área Construída (m2),Uso (IPTU),Descrição do uso (IPTU),Padrão (IPTU),Descrição do padrão (IPTU),ACC (IPTU)
0,8424500301,R GALIA,190,NaN,NaN,NaN,5602000,4.Arrematação (em leilão ou hasta pública),30459304.00,2023-10-26,...,Ativo Predial,8182,310.55,1.0000,7888,10,RESIDÊNCIA,15,RESIDENCIAL HORIZONTAL,2004.0
1,4212800055,R LOEFGREN,1401,UN 1404,VILA CLEMENTINO,NaN,4040031,2.Cessão de direitos relativos a compromisso d...,127130.82,2023-12-19,...,Ativo Predial,263,7.50,1.0000,385,31,"PRÉDIO DE ESCRITÓRIO OU CONSULTÓRIO, NÃO EM CO...",32,COMERCIAL HORIZONTAL,1962.0
2,1401200516,R AUGUSTA,2898,E 2900 UN 216,NaN,NaN,1412100,2.Cessão de direitos relativos a compromisso d...,181891.33,2023-12-19,...,Ativo Predial,278,5.05,1.0000,540,40,LOJA,33,COMERCIAL HORIZONTAL,1994.0
3,9035514653,AV WASHINGTON LUIS,1576,AP 152 E 4VGS,JD MARAJOARA,ED JEQUITIBA,4662902,8.Cessão de direitos hereditários (ou sucessór...,316666.66,2023-12-21,...,Ativo Predial,73836,89.91,0.0022,615,20,APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL),25,RESIDENCIAL VERTICAL,1992.0
4,10302548768,AV GUIDO CALOI,99999,"APT 211, TORRE A",SANTO AMARO,NaN,5802140,1.Compra e venda,299118.26,2023-12-20,...,Ativo Territorial,31351,227.54,1.0000,0,0,TERRENO,0,TERRENO,NaN
5,6420900328,R EUGENIO DE FREITAS,904,"APT 1612, TORRE 1",VILA GUILHERME,NaN,2060000,1.Compra e venda,214769.30,2023-12-22,...,Ativo Territorial,17065,105.80,1.0000,0,0,TERRENO,0,TERRENO,NaN
6,6420900328,R EUGENIO DE FREITAS,904,"APT 706, TORRE 1",VILA GUILHERME,NaN,2060000,1.Compra e venda,244236.33,2023-12-22,...,Ativo Territorial,17065,105.80,1.0000,0,0,TERRENO,0,TERRENO,NaN
7,6420900328,R EUGENIO DE FREITAS,904,"APT 1312, TORRE 1",VILA GUILHERME,NaN,2060000,1.Compra e venda,259737.81,2023-12-22,...,Ativo Territorial,17065,105.80,1.0000,0,0,TERRENO,0,TERRENO,NaN
8,6420900328,R EUGENIO DE FREITAS,904,"APT 109, TORRE 3",VILA GUILHERME,NaN,2060000,1.Compra e venda,272373.86,2023-12-22,...,Ativo Territorial,17065,105.80,1.0000,0,0,TERRENO,0,TERRENO,NaN
9,6420900328,R EUGENIO DE FREITAS,904,"APT 205, TORRE 3",VILA GUILHERME,NaN,2060000,1.Compra e venda,273101.65,2023-12-22,...,Ativo Territorial,17065,105.80,1.0000,0,0,TERRENO,0,TERRENO,NaN

In [4]:
auxiliar = df.loc[17]

auxiliar

N° do Cadastro (SQL)                                                       10144600667
Nome do Logradouro                                            AV PROF FRANCISCO MORATO
Número                                                                           99999
Complemento                                                           TORRE 1 APTO 908
Bairro                                                                             NaN
Referência                                                                         NaN
CEP                                                                            5521400
Natureza de Transação                                                 1.Compra e venda
Valor de Transação (declarado pelo contribuinte)                              288623.0
Data de Transação                                                  2023-12-20 00:00:00
Valor Venal de Referência                                                   33023338.0
Proporção Transmitida (%)                                                         0.03
Valor Venal de Referência (proporcional)                                     9907.0014
Base de Cálculo adotada                                                       288623.0
Tipo de Financiamento                                          2.Minha Casa Minha Vida
Valor Financiado                                                             230897.79
Cartório de Registro                                18º Cartório de Registro de Imóvel
Matrícula do Imóvel                                                             274408
Situação do SQL                                                      Ativo Territorial
Área do Terreno (m2)                                                             35983
Testada (m)                                                                       87.3
Fração Ideal                                                                       1.0
Área Construída (m2)                                                                 0
Uso (IPTU)                                                                           0
Descrição do uso (IPTU)                                                        TERRENO
Padrão (IPTU)                                                                        0
Descrição do padrão (IPTU)                                                     TERRENO
ACC (IPTU)                                                                         NaN
Name: 17, dtype: object

In [12]:
def limpa_preco(linha):
    linha['Natureza de Transação'] = linha['Natureza de Transação'].replace('1.','')
    return linha

In [13]:
limpa_preco(auxiliar)

N° do Cadastro (SQL)                                                       10144600667
Nome do Logradouro                                            AV PROF FRANCISCO MORATO
Número                                                                           99999
Complemento                                                           TORRE 1 APTO 908
Bairro                                                                             NaN
Referência                                                                         NaN
CEP                                                                            5521400
Natureza de Transação                                                   Compra e venda
Valor de Transação (declarado pelo contribuinte)                              288623.0
Data de Transação                                                  2023-12-20 00:00:00
Valor Venal de Referência                                                   33023338.0
Proporção Transmitida (%)                                                         0.03
Valor Venal de Referência (proporcional)                                     9907.0014
Base de Cálculo adotada                                                       288623.0
Tipo de Financiamento                                          2.Minha Casa Minha Vida
Valor Financiado                                                             230897.79
Cartório de Registro                                18º Cartório de Registro de Imóvel
Matrícula do Imóvel                                                             274408
Situação do SQL                                                      Ativo Territorial
Área do Terreno (m2)                                                             35983
Testada (m)                                                                       87.3
Fração Ideal                                                                       1.0
Área Construída (m2)                                                                 0
Uso (IPTU)                                                                           0
Descrição do uso (IPTU)                                                        TERRENO
Padrão (IPTU)                                                                        0
Descrição do padrão (IPTU)                                                     TERRENO
ACC (IPTU)                                                                         NaN
Name: 17, dtype: object

In [14]:
df.apply(lambda x: limpa_preco(x), axis=1) #axis=1 é rodar pelas linhas (igual a 0 é pelas colunas)

,N° do Cadastro (SQL),Nome do Logradouro,Número,Complemento,Bairro,Referência,CEP,Natureza de Transação,Valor de Transação (declarado pelo contribuinte),Data de Transação,...,Situação do SQL,Área do Terreno (m2),Testada (m),Fração Ideal,Área Construída (m2),Uso (IPTU),Descrição do uso (IPTU),Padrão (IPTU),Descrição do padrão (IPTU),ACC (IPTU)
0,8424500301,R GALIA,190,NaN,NaN,NaN,5602000,4.Arrematação (em leilão ou hasta pública),30459304.00,2023-10-26,...,Ativo Predial,8182,310.55,1.0000,7888,10,RESIDÊNCIA,15,RESIDENCIAL HORIZONTAL,2004.0
1,4212800055,R LOEFGREN,1401,UN 1404,VILA CLEMENTINO,NaN,4040031,2.Cessão de direitos relativos a compromisso d...,127130.82,2023-12-19,...,Ativo Predial,263,7.50,1.0000,385,31,"PRÉDIO DE ESCRITÓRIO OU CONSULTÓRIO, NÃO EM CO...",32,COMERCIAL HORIZONTAL,1962.0
2,1401200516,R AUGUSTA,2898,E 2900 UN 216,NaN,NaN,1412100,2.Cessão de direitos relativos a compromisso d...,181891.33,2023-12-19,...,Ativo Predial,278,5.05,1.0000,540,40,LOJA,33,COMERCIAL HORIZONTAL,1994.0
3,9035514653,AV WASHINGTON LUIS,1576,AP 152 E 4VGS,JD MARAJOARA,ED JEQUITIBA,4662902,8.Cessão de direitos hereditários (ou sucessór...,316666.66,2023-12-21,...,Ativo Predial,73836,89.91,0.0022,615,20,APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL),25,RESIDENCIAL VERTICAL,1992.0
4,10302548768,AV GUIDO CALOI,99999,"APT 211, TORRE A",SANTO AMARO,NaN,5802140,Compra e venda,299118.26,2023-12-20,...,Ativo Territorial,31351,227.54,1.0000,0,0,TERRENO,0,TERRENO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12146,4118401878,AV IBIJAU,364,AP 1716 E VAGA,MOEMA,NaN,4524020,4.Arrematação (em leilão ou hasta pública),162540.10,2023-11-30,...,Ativo Predial,2467,69.50,0.0048,91,25,FLAT RESIDENCIAL EM CONDOMÍNIO (EXIGE FRAÇÃO I...,23,RESIDENCIAL VERTICAL,1992.0
12147,8610700879,R BR DE JACEGUAI,1046,GARAGEM,NaN,NaN,4606901,Compra e venda,201522.39,2024-01-22,...,Ativo Predial,2800,40.00,0.1235,2503,24,GARAGEM (UNIDADE AUTÔNOMA) EM EDIFÍCIO EM COND...,23,RESIDENCIAL VERTICAL,1974.0
12148,11342201972,AV ANTONIO DIOGO,307,AP 23 BL 2,ED BETHA,RES GOLDEN LIFE,3669040,Compra e venda,255000.00,2024-01-15,...,Ativo Predial,4121,34.00,0.0063,91,20,APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL),21,RESIDENCIAL VERTICAL,2004.0
12149,15722919801,AV DOS OURIVES,632,AP 102 E VG,JARDIM SAO SAVERIO,TORRE 2,4194260,26.Cessão de direitos sobre o imóvel com alien...,94108.50,2024-01-15,...,Ativo Predial,7109,37.90,0.0043,79,20,APARTAMENTO EM CONDOMÍNIO (EXIGE FRAÇÃO IDEAL),22,RESIDENCIAL VERTICAL,2010.0
12150,10732300036,R SIN JUNQUEIRA,171,NaN,NaN,NaN,2840000,28.Excesso de meação ou quinhão na partilha (s...,508.07,2024-01-31,...,Ativo Predial,80,8.00,1.0000,50,10,RESIDÊNCIA,11,RESIDENCIAL HORIZONTAL,1970.0

In [19]:
df = df.drop(['N° do Cadastro (SQL)', 'Nome do Logradouro', 'Complemento', 'Bairro', 'Referência', 'CEP', 'Situação do SQL', 'Área do Terreno (m2)', 'Testada (m)',	'Fração Ideal',	'Área Construída (m2)',	'Uso (IPTU)', 'Valor Venal de Referência',	'Proporção Transmitida (%)','Valor Venal de Referência (proporcional)','Base de Cálculo adotada','Tipo de Financiamento','Valor Financiado','Cartório de Registro','Matrícula do Imóvel','Descrição do uso (IPTU)','Padrão (IPTU)','Descrição do padrão (IPTU)','ACC (IPTU)'], axis=1)

In [20]:
df

,Número,Natureza de Transação,Valor de Transação (declarado pelo contribuinte),Data de Transação
0,190,4.Arrematação (em leilão ou hasta pública),30459304.00,2023-10-26
1,1401,2.Cessão de direitos relativos a compromisso d...,127130.82,2023-12-19
2,2898,2.Cessão de direitos relativos a compromisso d...,181891.33,2023-12-19
3,1576,8.Cessão de direitos hereditários (ou sucessór...,316666.66,2023-12-21
4,99999,1.Compra e venda,299118.26,2023-12-20
...,...,...,...,...
12146,364,4.Arrematação (em leilão ou hasta pública),162540.10,2023-11-30
12147,1046,1.Compra e venda,201522.39,2024-01-22
12148,307,1.Compra e venda,255000.00,2024-01-15
12149,632,26.Cessão de direitos sobre o imóvel com alien...,94108.50,2024-01-15
12150,171,28.Excesso de meação ou quinhão na partilha (s...,508.07,2024-01-31